name: wg-blimp-testing
channels:
  - conda-forge
  - bioconda
dependencies:
  - bedtools
  - gembs 3.5.5_IHEC
  - bwa
  - bwameth
  - click
  - fastqc
  - git
  - h5py
  - methyldackel
  - metilene
  - mosdepth
  - multiqc
  - picard
  - pysam
  - qualimap
  - r-base
  - ruamel.yaml
  - samtools >=1.15
  - snakemake-minimal >=5.8
  - cython
  - pyyaml >=6.0
  - pkg-config
  - r-shiny
  - r-data.table
  - r-shinydashboard
  - r-htmlwidgets
  - r-dt  
